version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - echo "Running tests..."
      - echo "Tests passed"
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync build/ s3://sundhar-pipeline-bucket --delete
